C++/README.md
C++/factorial.cpp
README.md

C++ Algorithm added

---

C++/interpolation_search.cpp
C++/readme.md
README.md

interpolation search added

---

Python/README.md
Python/factorial.py
README.md

Python factorial code added

---

C/commont_element_in_two_arrays.c
README.md

- [*] Added a file in correct language folder
- [*] Followed [Piyush](https://github.com/piyush97) 
- [*] Starred the repository
- [*] Wrote about the algo in the Readme.md

Compare Elements in two Arrays

---

java/AnagramCheck.java

AnagramCheck.java

---

C++/BinarySearch.cpp

#11 Binary Search in cpp added

Created Binary Search in cpp

---

PULL_REQUEST_TEMPLATE.md
README.md
javascript/readme.md
javascript/selectionSort.js

Add algorithm

---

C++/heap_sort.cpp
README.md

C++ / Heap sort

---

C++/readme.md

#12 Updated Readme with Binary Search in c++

Updated Readme with Binary Search

---

C++/KMP(string-matching-algorithm).cpp
C++/N-Queen-Problem.cpp
C++/Tower-of-Hanoi.cpp
README.md

Added 3 algorithms and updated README as well

---

Java/Factorial.java
Java/README.md
README.md

Added Factorial algorithm in java language

---

Dart/hello_world.dart
README.md

Hello World in Dart

---

javascript/pascalTriangle
javascript/readme.md

Javascript pascal's triangle

---

C/SelectionSort.c
README.md

Added Selection Sort in C

---

PHP/insertionSort.php
README.md

create insertion sort for PHP

---

README.md
javascript/heapSort.js

create javascript heap sort

---

PHP/fibonnaci.php
PHP/readme.md
README.md

Add PHP Fibonacci

---

README.md
javascript/quickSort.js

create javascript quick sort

---

java/Fibonacci.java

Added Fibonacci.java

---

C/bubble_sort.c
C/insertion_sort.c
README.md

adds Bubble and Insertion Sort algorithms in C

---

C++/N_DigitFibonacciNumber
C++/readme.md

N Digit Fibonacci

---

README.md
java/KMP.java

added the KMP Algorithm in  java

---

Python/README.md
Python/selectionsort.py

Selection sort

---

C/count_sort.c
README.md

Added count_sort.c

---

C++/Fenwick_Tree.cpp

Fenwick Tree implementation code

---

C++/Lazy_propagation.cpp

Added code of segment_tree with Lazy propagation

---

C++/BFS.cpp

Added BFS implementation

---

C++/Graph_Hashmap.cpp

Create Graph using Hashmap

---

C++/Trie.cpp

Implement Trie using C++

---

Python/quicksort.py
README.md

Quicksort is a divide and conquer algorithm. It follows three steps:
Divide: partition the array into two subarrays such that each element of A[p..q-1] is less than or equal to A[q].
Conquer: sort the two subarrays by recursive calls to quicksort.

Added Quicksort.py file

---

Python/README.md

Updated Readme

---

recurrsionfactorial

find factorial using recurrsion

---

README.md
Ruby/README.md
Ruby/factorial.rb
Ruby/hello_world.rb

Factorial in ruby programming language

---

C++/LargestSumContigous.cpp

Efficient program to find the sum of contiguous subarray within a one-dimensional array of numbers which has the largest sum.
#kadane's Algorithm
Initialize:
max_so_far = 0
max_ending_here = 0
Loop for each element of the array
(a) max_ending_here = max_ending_here + a[i]
(b) if(max_ending_here < 0)
max_ending_here = 0
(c) if(max_so_far < max_ending_here)
max_so_far = max_ending_here
return max_so_far

LargesrSumContigous.cpp

---

C++/0-1-Knapsack.cpp
C++/readme.md
README.md

[Hacktoberfest] C++ 0/1 Knapsack problem optimal dynamic programming solution

---

Python/checkPalindromePython.py

Check for palindrome using python

---

C/Mountain.c

Add Mountian.c

---

BSEARCH.CPP

Binary Search in cpp

---

Bash/stringreversal.sh
README.md

Added bash string reversal

---

Bash/inserstionsort.sh
README.md

added insertionsort.sh

---

C++/huffman.cpp
README.md

added huffman in CPP

---

Bash/selectionsort.sh
README.md

added selectionsort.sh in Bash

---

Bash/radixsort.sh
README.md

added radixsort.sh in Bash

---

C++/coin_change.md

Implementing Coin Change problem DP.

coin_change.md

---

Python/towerOfHanoiPython.py

Tower of Hanoi implementation using python

---

Python/README.md

Added insertionSort.py and updated readme

---

C/helloWorld.c
README.md

Added helloWorld.c

---

C++/CountingSort.cpp
C++/readme.md
README.md

Added CountingSort.cpp and updated readme

---

C++/DSU.md

created dsu.md

---

Java/SignalProcessing/FFT.java

Add FFT algorithm in Java

---

README.md

Add FFT entry in README.md

---

Java/README.md

Add documentation about FFT in Java/README.md

---

Java/BitManipulation/ByteSwapper.java

Add Java ByteSwapper class

---

C++/segment_tree_sum_of_range.cpp
README.md

Added segment tree c++ program

---

Java/Bubble_Sort.java

Created Bubble_Sort.java

---

C++/triangleExistence.cpp
README.md

added an algorithm for check existance of a triangle.
update readme about

Create algorithm in c++ and doc about it

---

C++/fibo_series.cpp

added algo for fibonacci series in c++

---

Python/README.md
Python/dfs_python_adj_list.py
Python/multi.py
README.md

Added multi-process linear search and both types of DFS implementations

---

Python/README.md
Python/merge_sort_python.py
README.md

Mergesort - (Python) added

---

C++/matrix_multiply.cpp

Added matrix multiplication algorithm

---

C#/Triangle.cs
README.md

Triangle test int C#

---

C++/Selection Sort
palindrome.cpp

added an algorithm in c++

---

C++/Fibonacci Series

Create Fibonacci Series

---

C++/avltree.cpp
README.md

Added AVL tree implementation in cpp.

---

Java/linkedlist

LinkedList.java

---

Haskell/factorial.hs
Haskell/fibonacci.hs
Haskell/quicksort.hs
README.md

add fibonacci.hs factorial.hs and quicksort.hs

---

Java/Bubble_Sort.java

Optimised Bubble sort in java

---

C++/collatz_conjecture.cpp

Collatz conjecture in c++

---

C/Palindrome.c
README.md

Added a Algorithm in my favourite language

Palindrome of a string

---

README.md
javascript/mergeSort.js

I've added a merge sort algorithm to the javascript folder

Add mergeSort.js to the javascript folder

---

app.js
notes.js

It is a simple notes app using node.js

notes app using node.js

---

C/gcd.c
README.md

Helloworld using ruby

---

README.md
javascript/inorderTraversal.js
javascript/readme.md

Inorder Tree Traversal in JS

---

Haskell/fast-fibonacci.hs
README.md

Add fast Fibonacci algorithm

---

Haskell/mergesort.hs
README.md

Haskell merge sort

---

Haskell/dfs.hs
README.md

Haskell dfs

---

README.md
javascript/insertionSort.js

Added Insertion Sort Javascript

---

C/mergeSort.c
C/quickSort.c

- [] Followed [Piyush](https://github.com/piyush97) 
- [] Wrote about the algo in the Readme.md

Added mergesort and quicksort in c

---

C++/FACTORIAL1.cpp

Factorial algorithm

---

C++/Matrix_operations.cpp
README.md

The code which I submitted, performs basic matrix operations like add, subtract, multiply, transpose, sum of diagonal elements and checks the condition for Upper,Lower and Diagonal matrix.
In response to issue #1 
Thanks for your time Piyush!
-  ✅ Added a file in correct language folder 
(/C++)
-  ✅ Followed [Piyush](https://github.com/piyush97)
-  ✅ Starred the repository
-  ✅ Wrote about the algo in the Readme.md

Added a new C++ code!

---

Ruby/README.md
Ruby/insertion_sort.rb

Insertion sort added + Readme.md Updated

---

C/triangle.c

Triangle in C

---

javascript/insertionSort.js

Added Insertion Sort

---

C/heapsort.c

Added heapsort.c

---

README.md
solidity/hello-world.sol
solidity/sort-array.sol

add some algorithms of solidity lanaguage

---

C/Longest Common Subsequence.c

Added Longest Common Subsequence Algorithm in C Language

Longest Common Subsequence.c

---

Assembly/Mellody.txt

Mellody.txt created

---

Python/Decimal_to_Binary.py

create program to change decimal to binary format

---

C/BinarySearch.c
README.md

Binarysearch

---

javascript/recursionFactorial.js

algorithm resolved

---

Java/quickSort.java
README.md

Java Quick sort added  also tested

Java Quick sort added 

---

C/decimal_to_binary.c

Added decimal_to_binary.c

---

Python/BinarySearch.py

Added Binary Search in python

---

mergesort.c

Mergesort.c

---

C++/areaoftriangle.cpp
C++/insertionSort.cpp
C++/interval_scheduling.cpp
C++/josephus.cpp
C++/topological_sort.cpp
README.md

Few C++ Algorithms Added

---

PHP/primes
README.md

Added primes algo

---

C#/Fibonacci.cs
README.md

Hacktoberfest

---

javascript/mergeSort2.js

- Added another approach to mergeSort
- documented with comments

Hactoberfest- Documented MergeSort

---

javascript/Bloom Filter

A bloom filter is a space-efficient probabilistic data structure designed to test whether an element is present in a set. ... False positive matches are possible, but false negatives are not – in other words, a query returns either "possibly in set" or "definitely not in set".

Bloom filter

---

javascript/palindrome.js
javascript/pyramid.js

2 algos added to javascript folder

---

Python/0-1_knapsack_problem.py
Python/README.md

0-1 knapsack problem

---

Python/fibonacci.py

adding fibonacci series python program

---

Dart/linklist/Linkedlist.dart

Linkedlist algorithm in dart lang

---

PHP/bubbleSort.php
PHP/quickSort.php

Add Bubble  and Quick Sorts in PHP

---

Python/heapsort.py
README.md

Added heapsort.py

---

C++/SelectionSort.cpp

Selection Sort 

---

Python/Sieve Eratosthenes.py
README.md

Added new algorithm i.e Sieve of Eratosthenes 
The sieve of Eratosthenes is one of the most efficient ways to find all primes smaller than n when n is smaller than 10 million.

Added new Algorithm  Sieve of Eratosthenes

---

C++/parallelPI.c

Calculation PI through openMP.
Compilation requires -fopenmp to work

Parallel PI calc

---

README.md

Added my algorithm to C section

---

C++/counting_sort.cpp

added counting sort program in c++

---

C++/maxsubarr sum.cpp

added max subarray sum  program in c++

---

C++/merge_sort.cpp

added merge sort  program in c++

---

C++/bst_delete.cpp

added bst deletion in c++

---

Java/FizzBuzz.java
README.md

Added FizzBuzz beginner algorithm to Java

---

README.md
javascript/countingSort.js

Add Counting Sort in JavaScript

---

C++/eulersTotient.cpp
README.md

Add Euler's Totient Function

---

Python/ClippingVoronoi

Create Clipping Voronoi

---

Ruby/LinkedList.rb
Ruby/README.md
Ruby/binary_search_tree.rb
Ruby/stack.rb

add Stack, LinkedList, Binary Search Tree with Ruby Language
Update README.md

Add Ruby Stack, LinkedList, Binary Search Tree

---

C++/coinchange.cpp

added dp coin change

---

C++/kadane.cpp

added dp kadane algo

---

C++/knapsack01.cpp

added dp 01knapsack

---

C++/lcs.cpp
C++/subsum.cpp

added dp subset sum

---

C++/djikistra.cpp

added graph djikstra

---

C++/floyd-warshall.cpp
C++/kruskal.cpp

added graph floyd-warshall

---

C++/transitive closure.cpp

added transitive closure.cpp

---

C++/union-find.cpp

added union-find.cpp

---

C++/bfs.cpp
C++/ht.cpp

added tree bfs

---

javascript/hanoi-tower.js
javascript/readme.md

Add hanoi tower javascript algorithm

---

C/bubble-sort.c
C/radix_sort.c

Radix-Sort

---

Python/insertion_sorting.py

Created new python script insertion sort

---

Python/bucket_sort.py
README.md

Add new python scripts

---

README.md

Valid path for Dart/Linkedlist in Readme.md  

---

README.md

added queue in dart

---

README.md
Swift/bubble_sort.swift

Added bubble sort in Swift language

---

README.md
Ruby/reverse_string.rb

Add Ruby String Reversal Algorithm

---

README.md

Add link to dijkstra's implementation in readme.

---

C++/topological_sort_kahns.cpp
README.md

Added topological sort using kahn's algorithm
